#!/bin/sh
set -eu

REPOSITORY_ROOT_PATH="$(cd "$(dirname "$0")/.." && pwd)"
LOCAL_PROPERTIES_FILE_PATH="${REPOSITORY_ROOT_PATH}/local.properties"

DEBUG_BASE_URL_VALUE="${OGURI_DEBUG_BASE_URL:-}"
RELEASE_BASE_URL_VALUE="${OGURI_RELEASE_BASE_URL:-}"
KAKAO_KEY_VALUE="${OGURI_KAKAO_KEY:-}"
GOOGLE_WEB_CLIENT_ID_VALUE="${OGURI_GOOGLE_WEB_CLIENT_ID:-}"
AMPLITUDE_API_KEY_VALUE="${OGURI_AMPLITUDE_API_KEY:-}"

cat > "${LOCAL_PROPERTIES_FILE_PATH}" <<EOF
debug.base.url=${DEBUG_BASE_URL_VALUE}
release.base.url=${RELEASE_BASE_URL_VALUE}
kakao.key=${KAKAO_KEY_VALUE}
google.web.client.id=${GOOGLE_WEB_CLIENT_ID_VALUE}
amplitude.api.key=${AMPLITUDE_API_KEY_VALUE}
EOF

echo "Created local.properties for Xcode Cloud at ${LOCAL_PROPERTIES_FILE_PATH}"
