spring:
  application:
    name: oguri-api

  datasource:
    url: jdbc:postgresql://dpg-d6fgfl3uibrs73enkrjg-a.oregon-postgres.render.com:5432/oguri_postgres?sslmode=require
    username: oguri_postgres_user
    password: QhkOtLboo9XvYEfFPSyj9KLKqJMIcVGF
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: ${PORT:8080}
